(println "Enter first number:")
(def x (read-line))
(def x (Integer/parseInt x))
(println "Enter second number:")
(def y (read-line))
(def y (Integer/parseInt y))
(println "Enter third number:")
(def z (read-line))
(def z (Integer/parseInt z))

(defn exercise-math []
    (println (+ x y z))
    (println (* x y z))
    (println (/ x y z))
    (println (+ (Math/pow x 2)(* 3 y) z))
    (println (+(Math/pow z x)(Math/pow x z)))
    (println (+ (/ z y) x))
    (println (+ (* x y z) 1))
    (println (- (* x y z) 1))
)